def solution(puzzleinput):
    leftList, rightList = [], []
    # Ignore whitespace line generated by .split()
    n = len(puzzleinput)-1
    for i in range(n):
        parts = puzzleinput[i].strip().split("   ")
        l, r = parts
        leftList.append(int(l))
        rightList.append(int(r))
    
    leftList.sort()
    rightList.sort()
    totaldistance = 0
    for j in range(n):
        totaldistance += abs(leftList[j]-rightList[j])

    print(f"Solution: Total distance is {totaldistance}")

def part2(puzzleinput):
    leftList, rightFrequencies = [], {}
    # Ignore whitespace line generated by .split()
    n = len(puzzleinput)-1
    for i in range(n):
        parts = puzzleinput[i].strip().split("   ")
        l, r = parts
        leftList.append(int(l))
        rightFrequencies[int(r)] = rightFrequencies.get(int(r), 0) + 1
    
    similarityscore = 0
    for j in range(n):
        similarityscore += leftList[j] * rightFrequencies.get(leftList[j], 0)
    
    print(f"Solution: Total similarity score is {similarityscore}")

try:
    with open("input.txt", "r") as file:
        data = file.read()
        lines = data.split('\n')
except:
    print("input.txt file not found in current directory")

solution(lines)
part2(lines)