def solution(puzzleinput):
    leftlist, rightlist = [], []
    # Ignore whitespace line generated by .split()
    n = len(puzzleinput)-1
    for i in range(n):
        parts = puzzleinput[i].strip().split("   ")
        l, r = parts
        leftlist.append(int(l))
        rightlist.append(int(r))
    
    leftlist.sort()
    rightlist.sort()
    totaldistance = 0
    for i in range(n):
        totaldistance += abs(leftlist[i]-rightlist[i])

    print(f"Solution: Total distance is {totaldistance}")

try:
    with open("input.txt", "r") as file:
        data = file.read()
        lines = data.split('\n')

    solution(lines)
except:
    print("input.txt file not found in current directory")